### ISSUE TITLE
Missing Ability to Set HTTP Headers

### ISSUE THREAD

**Issue by rebeccaskinner** [imalsogreg/dhallia#6]
Missing the ability to set HTTP headers.

**Comment by rebeccaskinner** [comment]
This should be trivial to add, the logic will be similar to supporting query parameters.

**Comment by srenatus** [comment]
💭 I believe this was added recently: https://github.com/imalsogreg/dhallia/commit/069b7240330bd0fb952c8c786e73c78f297bee5a#diff-6af8b196f66ae1ecb24e9c3865f3e917R12 and https://github.com/imalsogreg/dhallia/commit/069b7240330bd0fb952c8c786e73c78f297bee5a#diff-60201a63c1495ff0e892276fbac715b9R133 etc .... or did you mean *response headers*? 🤔

**Comment by imalsogreg** [comment]
@srenatus Oops, yes thanks! We have request headers now. Adding handling for response headers is a bigger task, since right now we don't support *any* special handling of responses in raw APIs - the only thing we do is naively convert their response body to json.
